# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target '냉장고 좀 부탁해' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for 냉장고 좀 부탁해
   pod 'RxCocoa', '6.5.0'
   pod 'SnapKit'
   pod 'Charts'
   pod 'FSCalendar'
   pod 'ReactorKit'
   pod 'Realm'

end
